# -*- coding: utf-8 -*-
"""2nd_scenario_data_generate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOsFFYzVEuJPdLzbhdqM96AuZ169KQVo
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime

dep = pd.read_csv('/content/route.txt', sep = ',')
dep_list=dep.iloc[:,0].unique().tolist()
route=dep.values.tolist()

dep

def date_range(start, end):
    start = datetime.strptime(start, "%m월 %d일")
    end = datetime.strptime(end, "%m월 %d일")
    dates = [date.strftime("%-m월 %-d일") for date in pd.date_range(start, periods=(end-start).days+1)]
    return dates

date = date_range("1월 1일", "12월 31일")
people=['일반',	'중고생',	'아동',	'국가유공자',	'성인',	'어른',	'어린이',	'아기',	'애기',	'초등학생',	'청소년',	'중학생',	'고등학생']
now=['지금','당장','빨리','현재','최대한 빨리','가장 빠른','가장 빨리']
forward_time=['낮','오전','오후','밤','저녁','아침','새벽']
date_exact=['오늘','익일','금일','명일','내일','모레','내일 모레','보름']
date_not_exact=['이번주','다음주','다다음주']
date_not_exact_with_int=['주 뒤','일 뒤','주일 뒤']
day=['월요일','화요일','수요일','목요일','금요일','토요일','일요일']

some_date=pd.Series([date, date_exact, now], index=['date', 'date_exact', 'now'])
some_date

def get_route():
  st=random.choice(dep_list)
  match=[i for i in range(len(route)) if route[i][0]==st]
  end=route[random.choice(match)][1]
  return "/DEP;"+st+'/', "/ARR;"+end+'/'

def get_date(i):
  return '/DATE;'+random.choice(some_date[i])+'/'

#ex.이번주 월요일
def get_date_with_day():
  return '/DATE;'+random.choice(date_not_exact)+' '+random.choice(day)+'/'

#ex.1주일 뒤
def get_date_not_exact_int():
  return '/DATE;'+str(np.random.randint(1,6))+random.choice(date_not_exact_with_int)+'/'

#ex. 낮 12시
def get_dtime_hour():
  return '/DEP_TIME;'+random.choice(forward_time)+' '+str(np.random.randint(1,12))+'시'+'/'

#ex. 18시
def get_dtime_full_hour():
  return '/DEP_TIME;'+str(np.random.randint(0,24))+'시'+'/'

#ex. 낮 12시 30분, 낮 12시 반
def get_dtime_hour_exact_min():
  return '/DEP_TIME;'+random.choice(forward_time)+' '+str(np.random.randint(1,12))+'시'+random.choice(['반',str(np.random.randint(1,60))+'분'])+'/'

#ex. 18시 30분
def get_dtime_full_hour_exact_min():
  return '/DEP_TIME;'+str(np.random.randint(0,24))+'시'+random.choice(['반',str(np.random.randint(1,60))+'분'])+'/'

#ex. 12시간 뒤
def get_dtime_hour_later():
  return '/DEP_TIME;'+str(np.random.randint(1,12))+random.choice(['시간 뒤','시간 후'])+'/'

#ex. 30분 뒤
def get_dtime_min_later():
  return '/DEP_TIME;'+str(np.random.randint(1,60))+random.choice(['분 뒤','분 후'])+'/'

def get_atime_hour():
  return '/ARR_TIME;'+random.choice(forward_time)+' '+str(np.random.randint(1,12))+'시'+random.choice(['',' 반'])+'/'

def get_atime_hour_exact_min():
  return '/ARR_TIME;'+random.choice(forward_time)+' '+str(np.random.randint(1,12))+'시'+str(np.random.randint(1,60))+'분'+'/'

def get_atime_hour_later():
  return '/ARR_TIME;'+str(np.random.randint(1,12))+random.choice(['시간 뒤','시간 후'])+'/'

def get_atime_full_hour():
  return '/ARR_TIME;'+str(np.random.randint(0,24))+'시'+'/'

def get_atime_full_hour_exact_min():
  return '/ARR_TIME;'+str(np.random.randint(0,24))+'시'+random.choice(['반',str(np.random.randint(1,60))+'분'])+'/'

reserve=['예약','예매']
ending=['할래','해줘','해','하려 해','하려하는데 표 있어?']

bus_list_d_1=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_1.append(start+'에서 '+end+'로 가는 버스 '+random.choice(reserve)+random.choice(ending))

bus_list_d_2=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_2.append(end+'로 가는 버스 '+random.choice(reserve)+random.choice(ending)+'. '+start+'에서 출발할꺼야')

bus_list_d_3=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_3.append(end+'로 가는 버스 '+random.choice(reserve)+random.choice(ending)+'. '+start+'에서 출발하는 걸로')

bus_list_d_4=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_4.append(end+'로 가는 버스 '+random.choice(reserve)+random.choice(ending)+'. '+start+'출발')

bus_list_d_5=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_5.append(start+'에서 출발해서 '+end+'로 도착하는 버스 '+random.choice(reserve)+random.choice(ending))

bus_list_d_6=[]
for i in range(800):
  start, end = get_route()
  bus_list_d_6.append(start+'출발 '+end+'도착 버스 '+random.choice(reserve)+random.choice(ending))

bus_list=bus_list_d_1+bus_list_d_2+bus_list_d_3+bus_list_d_4+bus_list_d_5+bus_list_d_6

bus_list

reject=['','아니 ','음.. ','음.. 아니 ','아니야 ']
change=['로','로 바꿀게','로 수정해줘','로 바꿔 줘','로 바꿔 주세요','로 수정할게']
dep_change=['에 출발','에 출발하는 걸','출발']
arr_change=['에 도착','도착']

###출발 

#ex.1월 1일 낮 12시 (출발)로 바꿀게, 내일로 바꿀게
sec_bus_list_1=[]
for i in range(1000):
  sec_bus_list_1.append(random.choice(reject)+random.choice(['',get_date_with_day(),get_date_not_exact_int(),get_date(random.choice([0,1]))])+random.choice([get_dtime_hour(),get_dtime_full_hour()])+random.choice(dep_change)+random.choice(change))

#ex.아니 지금
sec_bus_list_2=[]
for i in range(50):
  sec_bus_list_2.append(random.choice(reject)+get_date(2))

#ex.아니 이번주 월요일 낮 12시 30분으로 바꿀게
sec_bus_list_3=[]
for i in range(1000):
  sec_bus_list_3.append(random.choice(reject)+random.choice(['',get_date_with_day(),get_date_not_exact_int(),get_date(random.choice([0,1]))])+' '+random.choice([get_dtime_hour_exact_min(),get_dtime_full_hour_exact_min()])+'으'+random.choice(change))

#ex.아니 이번주 월요일 낮 12시 30분 출발로 바꿀게
sec_bus_list_4=[]
for i in range(1000):
  sec_bus_list_4.append(random.choice(reject)+random.choice(['',get_date_with_day(),get_date_not_exact_int(),get_date(random.choice([0,1]))])+' '+random.choice([get_dtime_hour_exact_min(),get_dtime_full_hour_exact_min()])+random.choice(dep_change)+random.choice(change))

#ex.아니 12시간 뒤 (출발)로 바꿀게
sec_bus_list_5=[]
for i in range(100):
  sec_bus_list_5.append(random.choice(reject)+random.choice([get_dtime_hour_later(),get_dtime_min_later()])+random.choice(dep_change)+random.choice(change))


### 도착

#ex.아니 1월 1일 낮 12시 도착으로 바꿀게
sec_bus_list_6=[]
for i in range(1000):
  sec_bus_list_6.append(random.choice(reject)+random.choice(['',get_date_with_day(),get_date_not_exact_int(),get_date(random.choice([0,1]))])+random.choice(['',get_atime_hour(),get_atime_hour_exact_min(),get_atime_hour_later(),get_atime_full_hour(),get_atime_full_hour_exact_min()])+random.choice(arr_change)+'으'+random.choice(change))

#ex.아니 1월 1일 낮 12시에 도착하는걸로 바꿀게
sec_bus_list_7=[]
for i in range(500):
  sec_bus_list_7.append(random.choice(reject)+random.choice(['',get_date_with_day(),get_date_not_exact_int(),get_date(random.choice([0,1]))])+random.choice(['',get_atime_hour(),get_atime_hour_exact_min(),get_atime_hour_later(),get_atime_full_hour(),get_atime_full_hour_exact_min()])+'에 도착하는 걸'+random.choice(change))



bus_list_change=sec_bus_list_1+sec_bus_list_2+sec_bus_list_3+sec_bus_list_4+sec_bus_list_5+sec_bus_list_6+sec_bus_list_7

bus_list_change

